#####################################################################
#
# INPUT_DIR: Input directory for images
# OUTPUTDIR: Output direcotry to save processed images
#
#####################################################################
INPUT_SEG_DIR = "./dataset/input/"
OUTPUT_SEG_DIR = "./dataset/output/"
FILE_EXTENSION = ".BMP"

# The number of process workers in the process pool for work on batches
NUM_OF_PROCESSES = 10


#################################################
#
# COLOR_CHANNEL: Color channel "R", "B" or "G"
#
#################################################
COLOR_CHANNEL = "G"